### PR TITLE
Update README.md, fix dependency issue, Comment why can't remove pip package cleanly

### PR DESCRIPTION
**Pull request by mojibake-umd**
Just noticed that previous pull request was accepted. Did not expect that...
Actually trying to make sure the pip install package is removed first does not work.
This acknowledges that.

### CODE REVIEW

**Comment by pcfens** [comment]
Thanks for fixing the module up - it's probably pretty obvious that I don't do much with it anymore. Even though I don't have time to update it myself I'm always happy to accept PRs for it for others that still use it.

It's not letting me merge in your comments because of a conflict. I'm guessing a rebase will take care of things though if you can.

Thanks again!

**Comment by mojibake-umd** [comment]
@pcfens 

Thanks... Merge should be clean now.

**Comment by mojibake-umd** [comment]
Marked work in progress. Realized I need to fix a dependency issue.

**Comment by mojibake-umd** [comment]
OK to merge now.

**Comment by mojibake-umd** [comment]
If code updates are required to make new version release to Puppet forge, let me know and I can attempt to work later. Forge probably want modules to be PDK ready going forward. Just learning PDK myself.

**Comment by pcfens** [comment]
The `pdk convert` command worked fine, but I didn't take the time to fix the Ruby code so the Rubocop stuff would pass. I uploaded the converted command to the forge as v0.4.0 too. Thanks a ton for your help.

**Pull request merged**
